#on:
#  push:
#    tags:
#       - '*'
on: [push] # for testing out

name: build releases

jobs:
  linux_x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build
        run: cargo build --all --release && strip target/release/cf-app-log-detector && mv target/release/cf-app-log-detector target/release/cf-app-log-detector-linux
  darwin:
    name: Mac OS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
          default: true
      - name: Build for mac
        run: cargo build --all --release && strip target/release/cf-app-log-detector && mv target/release/cf-app-log-detector target/release/cf-app-log-detector-mac

